### PR TITLE
Fix icon installation target location (fixes #5)

### LINKED ISSUE #5: Some action icons are missing
The icons of the _Load Executable_ and _Set Breakpoint_ actions are missing. This happens for the KF5-based release 3.0.0.

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #5

- `/usr/share/kdbg/icons/oxygen/22x22/` is not searched, bad
- `/usr/share/kdbg/icons/hicolor/22x22/` is searched, good

### CODE REVIEW

**Comment by j6t** [comment]
The commit that renames to `executable-open` lacks an explanation why that is needed. I can update the commit message accordingly, if you don't mind.

**Comment by j6t** [comment]
Thanks, looking good!

**Comment by hartwork** [comment]
@j6t cool! Anything left before a merge?

**Comment by j6t** [comment]
No, thanks, not at the moment.

**Comment by hartwork** [comment]
@j6t but you would like to not merge yet just to reflect on it more?

**Comment by j6t** [comment]
> but you would like to not merge yet just to reflect on it more?

Yes, so to speak. I have not yet made up my mind how I want the merge history to look like.

**Comment by hartwork** [comment]
@j6t interesting! There are at least three options with rather different pros and cons:
- a) merge commit — gives history where the start and the end of the pull request are preserved and visible and keeps original SHA1s
- b) rebase — forces linear history but with new SHA1s
- c) squash — also forces linear history but gets rid of inter-commit cutting for good or for bad
- d) fast-forward — like rebase but with original SHA1s, often not possible and not accessible via GitHub UI

Personally I'd recommend against (c) in our very case because it's two commits intentionally and that would be lost. What are your thoughts on the options so far?

**Comment by j6t** [comment]
Thanks for the education, but that would not have been necessary.

I've not yet made up my mind which of your branches I'll fast-forward and which one I merge. Or if I fast forward one of my own commits (that I haven't shown, yet) and merge all of yours. I plan to fast-forward the "most straight-forward" commits and merge the others.

**Comment by hartwork** [comment]
@j6t if it was up to me it would be a clear "all else after CI, CI first" because that will point out potential problems with the unpushed commits about to come and will allow addressing those if any before putting these commits on `master`. Are there other aspects that would matter in terms of what to forward and what to merge and in which order? Can you help me understand what you are aiming to optimize for?

**Comment by hartwork** [comment]
@j6t any news?

**Comment by j6t** [comment]
Sorry, I have to put this project on the backburner. I hope I'll get back to it over the weekend.

**Comment by hartwork** [comment]
@j6t thanks a lot for the two merges! :pray: :tada:

**Pull request merged**
