### PR TITLE
Switch away from using deprecated methods

### PR DESCRIPTION
**Pull request by davispuh**
These methods have been deprecated and are removed from Qt6

### CODE REVIEW

**Comment by j6t** [comment]
Thank you for this contribution. I'm still reviewing the changes.

One thing I noticed is that the removal of the `KWindowSystem` breaks the intended behavior in an unacceptable way. To test it, debug a GUI application that covers the entire screen, set a breakpoint that is hit long after the application has already covered the window. When the breakpoint is finally reached, the KDbg window no longer comes to the foreground, but stays invisible behind the application window, which does not respond anymore.

Is `KWindowSystem` not available anymore in later KDE toolkits?

**Review by j6t — CHANGES_REQUESTED** [review]
The justification of this patch does not match the patch text. The changed lines do not involve `operator=`. Either it is that in Qt6 the constructor `QFileInfo(const QString&)` is `explicit`, or this change is not necessary.

**Comment by j6t** [comment]
The justification of patch 6406501 does not match the patch text. The changed lines do not involve `operator=`. Either it is that in Qt6 the constructor `QFileInfo(const QString&)` is `explicit`, or the change is not necessary.

The other commits except for 5dd3d4b (as mentioned earlier) are fine.

If you repost the series, I would appreciate if you could complete sentences in the commit messages with a fullstop, including the title texts. I.e., follow the pattern of the existing commits.

**Comment by davispuh** [comment]
> One thing I noticed is that the removal of the `KWindowSystem` breaks the intended behavior in an unacceptable way. To test it, debug a GUI application that covers the entire screen, set a breakpoint that is hit long after the application has already covered the window. When the breakpoint is finally reached, the KDbg window no longer comes to the foreground, but stays invisible behind the application window, which does not respond anymore.

I didn't really test it but I think using `KWindowSystem` for this purpose is wrong. `QWidget::activateWindow()` should work, if you look at documentation https://doc.qt.io/qt-5/qwidget.html#activateWindow it says

> This function performs the same operation as clicking the mouse on the title bar of a top-level window. On X11, the result depends on the Window Manager. If you want to ensure that the window is stacked on top as well you should also call [raise](https://doc.qt.io/qt-5/qwidget.html#raise)(). Note that the window must be visible, otherwise activateWindow() has no effect.
> 
> On Windows, if you are calling this when the application is not currently the active one then it will not make it the active window. It will change the color of the taskbar entry to indicate that the window has changed in some way. This is because Microsoft does not allow an application to interrupt what the user is currently doing in another application.

We are doing exactly correct thing and if it doesn't work it means it's a bug in Qt/Window Manager. But note as you can see Windows doesn't support this and it's up to Window Manager to decide whether to honor this. Also currently there's no such functionality on Wayland - similarly as on Windows, applications can't activate themselves.

Basically the way how it needs to be implemented is that Qt should request activation and then it submits request to compositor which then based on user preference configuration (eg. allow this app to bring itself to front or don't allow that) would either respect or ignore this request. Using X11 directly is just a hack and it only works because there's no security and any X11 client can do anything they want.

And that "Note that the window must be visible, otherwise activateWindow() has no effect." I would challenge it at Qt side that if user allowed this then Qt should respect that and still activate window even in this case.

> Is `KWindowSystem` not available anymore in later KDE toolkits?

`KWindowSystem` was split in 2 parts. Things are work on both X11 and Wayland stays in it but X11 specific things were moved to `KX11Extras`. See https://invent.kde.org/frameworks/kwindowsystem/-/commit/7cfd7c36eb017242d7a0202db82895be6b8fb81c so it can be ported that way but it would be X11-only solution and I think better just fix it properly in Qt/KWin.

Anyway I dropped that commit from this PR.

> The justification of patch https://github.com/j6t/kdbg/commit/64065013dca65da5053f9632895a40675a1e8a89 does not match the patch text. The changed lines do not involve operator=. Either it is that in Qt6 the constructor QFileInfo(const QString&) is explicit, or the change is not necessary.

Yeah I don't really know C++ :sweat_smile: don't know why it fails but it fails and this fixes. I reworded commit message.


> If you repost the series, I would appreciate if you could complete sentences in the commit messages with a fullstop, including the title texts. I.e., follow the pattern of the existing commits.

Added periods to commit messages.

**Comment by j6t** [comment]
Thank you for the contribution. I've integrated the updated patches.

Regarding the use or not of `KWindowSystem`, I have tested your patch, and it does not do the intended things here for me. I am aware that it might not be the intended way to forcefully move windows to the top *in general*, but I consider the case where a debuggee is stopped  and the debugger (KDbg) requires attention a special case that deserves special treatment, even though it needs quite some force to achieve the desired effect. And, BTW, even though on Windows an application cannot move itself to the foreground *in general*, the Visual Studio IDE *can* do so nevertheless. (I don't know what means they are leveraging to achieve the effect.)

**Comment by davispuh** [comment]
My point is, it needs to be submitted as bug report to KWin/Qt to support this use case. So that it is also implemented in Wayland because currently this approach wouldn't even work there.
If this had been done years ago maybe today we would have a proper way :P

**Pull request merged**
