### PR TITLE
Get translations back in sync + enforce that they stay in sync (targetting `master-ci-check`)

### PR DESCRIPTION
**Pull request by hartwork**
@j6t what do you think?

### CODE REVIEW

**Review by j6t — COMMENTED** [review]
Why? What is this good for?

**Comment by j6t** [comment]
> Why? What is this good for?

See? What piece of *it is this review system when *you* as the contributor do not know that I made this comment on a particular commit, not the whole PR??

**Comment by j6t** [comment]
> [d8f2605](https://github.com/j6t/kdbg/pull/38/commits/d8f2605ebe11a282dc90d930ddc91ba45b0e710c)

No way. I do not want to update *.po just because line numbers changed, and I do not want see CI failures just because *.po was not updated.

**Comment by hartwork** [comment]
> Why? What is this good for?

@j6t I would think that "enforce that they stay in sync" says that very clear, it fails the CI when things are not in sync :smiley: 

> > Why? What is this good for?
> 
> See? What piece of *it is this review system when _you_ as the contributor will not know that I made this comment on a particular commit ([aed5342](https://github.com/j6t/kdbg/pull/38/commits/aed5342744c7a18828d249786ccab7063317ec8f)), not the whole PR!!

I cannot confirm that you commented on a single commit. You probably just didn't :smiley: 


> > [d8f2605](https://github.com/j6t/kdbg/pull/38/commits/d8f2605ebe11a282dc90d930ddc91ba45b0e710c) Enforce that .pot and .po files remain in sync
> 
> No way. I do not want to update *.po just because line numbers changed, and I do not want see CI failures just because *.po was not updated.

Okay. it works well for libvisual: https://github.com/Libvisual/libvisual/blob/0.4.x/.github/workflows/translations.yml

> BTW, please do not build on top of branch `master-ci-check`. Build on `master` (or `maint`).

Okay, I was thinking I would do you a favor, the diff towards `master` is probably slightly different.

I guess I'll close as won't fix. Let me know if you change your mind, this was the right approach to the problem: Stop going out of sync right where it's introduced. Alright, I tried.

**Comment by j6t** [comment]
> > Why? What is this good for?
> 
> @j6t I would think that "enforce that they stay in sync" says that very clear, it fails the CI when things are not in sync 😃

Well, the text just says *what* the change introduces, but it does not state the problem that it solves. The *why* is missing.

> 
> > > Why? What is this good for?
> > 
> > 
> > See? What piece of *it is this review system when _you_ as the contributor will not know that I made this comment on a particular commit ([aed5342](https://github.com/j6t/kdbg/pull/38/commits/aed5342744c7a18828d249786ccab7063317ec8f)), not the whole PR!!
> 
> I cannot confirm that you commented on a single commit. You probably just didn't 😃

See? That's *exactly* what I mean. **Of course** did I comment on the change alone. I clicked the link, I was shown the commit *and only this commit*; I was given the opportunity to "Review changes" (the green button in the upper right). **Of course** I expect that the comment applies to the commit *and only to this commit*. Yet, GitHub inserted the comment as if it was about the entire PR. *That's* why this review system is inferior.

> 
> > > [d8f2605](https://github.com/j6t/kdbg/pull/38/commits/d8f2605ebe11a282dc90d930ddc91ba45b0e710c) Enforce that .pot and .po files remain in sync
> > 
> > 
> > No way. I do not want to update *.po just because line numbers changed, and I do not want see CI failures just because *.po was not updated.
> 
> Okay. it works well for libvisual: https://github.com/Libvisual/libvisual/blob/0.4.x/.github/workflows/translations.yml

Perhaps they have a different workflow?

**Comment by hartwork** [comment]
> > @j6t I would think that "enforce that they stay in sync" says that very clear, it fails the CI when things are not in sync 😃
> 
> Well, the text just says _what_ the change introduces, but it does not state the problem that it solves. The _why_ is missing.

@j6t "enforce that they stay in sync" comes with a free "because we do not want them to be out of sync", it hardly gets any more obvious. There is no why missing here. 

> > Okay. it works well for libvisual: https://github.com/Libvisual/libvisual/blob/0.4.x/.github/workflows/translations.yml
> 
> Perhaps they have a different workflow?

One that prevents introduction of issues by design, that is correct.

**Comment by j6t** [comment]
> > > @j6t I would think that "enforce that they stay in sync" says that very clear, it fails the CI when things are not in sync 😃
> > 
> > 
> > Well, the text just says _what_ the change introduces, but it does not state the problem that it solves. The _why_ is missing.
> 
> @j6t "enforce that they stay in sync" comes with a free "because we do not want them to be out of sync", it hardly gets any more obvious. There is no why missing here.

If by "out of sync" we mean the same thing, then KDbg's translation was out of sync most of the time. But there never was a user-visible malfunction attached to it, at least not one that would be fixed by "stay in sync". So, what is it that is solved by "stay in sync"?

**Comment by hartwork** [comment]
@j6t I'll leave it at that. If you choose to be okay with them going out of sync, good, I don't.

**Pull request closed without merging**
