### PR TITLE
Add simple CI based on GitHub Actions (fixes #29)

### LINKED ISSUE #29: Contributing simple Linux CI based on GitHub Actions welcome?
Hi!

I noticed that this repository does not have any CI so that currently pull requests could in theory break compilation unnoticed any time even with careful review. Use of GitHub Actions would be free of cost for you, works well, and only requires addition of a single YAML file to activate. I'm thinking of an approach similar to https://github.com/projectM-visualizer/frontend-libvisual-plug-in/blob/master/.github/workflows/linux.yml , aiming to cover at least GCC 12 and Clang 17 here. What do you think? 

Best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #29

A successful run from this very code can be seen in my fork at https://github.com/hartwork/kdbg-fork/actions/runs/6633232350 .

### CODE REVIEW

**Comment by j6t** [comment]
What is the reason to test both clang 17 and clang 18? Just because we  can?

What happens when a CI run fails? And what if it is not acted on immediately?

**Comment by hartwork** [comment]
> What is the reason to test both clang 17 and clang 18? Just because we can?

@j6t Clang 18 is what is in the making. We can either (a) test with pre-release Clang 18 to know whenever things break or (b) upgrade to Clang 18 once it is final and then fix all breakage at once. I'm good either way, do you want me to drop Clang 18 from the CI?

> What happens when a CI run fails? And what if it is not acted on immediately?

When the run fails, the related commit (and pull request) will be marked as failing CI, you would then make further changes to the pull request unti9l it is green and then merge the pull request, keeping `master` CI-green at all times. You could technically merge a red pull request but then the CI can no longer work at full value. Does that make sense?

**Comment by j6t** [comment]
> @j6t Clang 18 is what is in the making. We can either (a) test with pre-release Clang 18 to know whenever things break or (b) upgrade to Clang 18 once it is final and then fix all breakage at once. I'm good either way, do you want me to drop Clang 18 from the CI?

I prefer a minimal maintenance version. If there is something to change in the CI script just because Clang 18 transitioned from preview to released, than it must go. Otherwise, it can stay.

> > What happens when a CI run fails? And what if it is not acted on immediately?
> 
> When the run fails, the related commit (and pull request) will be marked as failing CI, you would then make further changes to the pull request unti9l it is green and then merge the pull request, keeping `master` CI-green at all times. You could technically merge a red pull request but then the CI can no longer work at full value. Does that make sense?

So, how do I test my own changes? I don't use pull requests at all. Do I have to push `master` to a work-in-progress branch to get it CI-tested before I push it out for real?

**Comment by hartwork** [comment]
> I prefer a minimal maintenance version. If there is something to change in the CI script just because Clang 18 transitioned from preview to released, than it must go. Otherwise, it can stay.

@j6t alright, removed.


> So, how do I test my own changes? I don't use pull requests at all. Do I have to push `master` to a work-in-progress branch to get it CI-tested before I push it out for real?

There are (at least two ways):
- a) Make a new feature branch, push it, check the CI results, merge to `master` when ready, push `master`.
- b) Make a new feature branch, push it, make it a pull request, adjust until the CI is green, click the "merge" button.

That plus potentially [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) on top.

What do you think?

**Review by j6t — CHANGES_REQUESTED** [review]
On my system (openSUSE 15.4) `qmake` is actually `qmake-qt5`. Would you mind augmenting the commit with another option?

What do you think about a commit message like this:

> Do not hard-code Qt5 installation paths in kdbg/testprogs/Makefile.
>
> We are going to add CI support, and will do it in such a way that
> it also compiles the files in kdbg/testprogs. However, the CI system's
> Qt5 libraries are installed in locations different from those expected
> by the Makefile. Use qmake to derive the installation paths.

**Comment by hartwork** [comment]
@j6t thanks for the review! I have now…

- added `qmake-qt5` before unversioned `qmake`
- used the extract proposed commit message
- added you as a co-author

Pushed.

**Pull request merged**
